from __future__ import annotations

from typing import Literal

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from aethon.auth import current_owner, security
from aethon.model_router import ModelRouter

router = APIRouter(prefix="/v1/coding", tags=["coding"])
_model = ModelRouter()

Mode = Literal["create", "debug", "explain", "review", "tests", "refactor"]


class CodingRequest(BaseModel):
    model_config = {"extra": "forbid"}

    request: str = Field(min_length=3, max_length=12000)
    mode: Mode = "create"
    language: str = Field(default="auto", min_length=1, max_length=80)
    framework: str = Field(default="", max_length=120)
    code: str = Field(default="", max_length=30000)
    error: str = Field(default="", max_length=12000)
    constraints: str = Field(default="", max_length=6000)


def owner(credentials=Depends(security)) -> str:
    return current_owner(credentials)


def build_coding_prompt(payload: CodingRequest) -> str:
    mode_instructions = {
        "create": "Design and implement the requested solution. Give complete, runnable code, file names, setup/run commands, and a short explanation. If multiple files are needed, label each file clearly.",
        "debug": "Diagnose the provided code and error. Identify the likely root cause, then provide a corrected complete code or a minimal exact patch, plus steps to reproduce and verify.",
        "explain": "Explain the code accurately in clear steps, including important concepts, inputs, outputs, complexity when relevant, and a small example.",
        "review": "Review for correctness, edge cases, security, maintainability, performance, and accessibility where relevant. Prioritize findings by severity and give concrete fixes.",
        "tests": "Create meaningful automated tests for normal cases, edge cases, and failure cases. State exact commands to run them. Do not claim tests were executed.",
        "refactor": "Improve structure, readability, type safety, and maintainability while preserving behavior. Explain behavior-changing suggestions separately.",
    }
    sections = [
        "You are AETHON Coding Engineer, a senior software engineer and practical coding tutor.",
        "Be direct, conversational, and implementation-first. Respect the user's existing stack and code. Do not rewrite an existing project from scratch unless explicitly requested.",
        "Prefer correct, secure, maintainable, runnable solutions over vague advice. Include exact filenames, complete code or precise patches, dependencies, commands, and verification steps as appropriate.",
        "For code with external effects, secrets, destructive operations, or device access, explain the risk and require authorization/confirmation before execution. Never expose secrets.",
        "Never claim you created files, ran code, passed tests, installed packages, or deployed anything unless a connected tool actually did so. If execution tools are unavailable, say the code is unexecuted and provide verification commands.",
        "If essential requirements are missing, state reasonable assumptions and proceed; ask a question only when blocked.",
        f"MODE: {payload.mode}. {mode_instructions[payload.mode]}",
        f"LANGUAGE: {payload.language}",
        f"FRAMEWORK: {payload.framework or 'Choose an appropriate framework if needed.'}",
        f"USER REQUEST:\n{payload.request}",
    ]
    if payload.constraints:
        sections.append(f"CONSTRAINTS:\n{payload.constraints}")
    if payload.code:
        sections.append(f"EXISTING CODE:\n{payload.code}")
    if payload.error:
        sections.append(f"ERROR / LOGS:\n{payload.error}")
    return "\n\n".join(sections)


@router.get("/health")
def coding_health(owner_id: str = Depends(owner)) -> dict:
    return {"ok": True, "skill": "coding", "modes": ["create", "debug", "explain", "review", "tests", "refactor"]}


@router.post("/assist")
def coding_assist(payload: CodingRequest, owner_id: str = Depends(owner)) -> dict:
    prompt = build_coding_prompt(payload)
    try:
        result = _model.generate(prompt, user_text=payload.request)
    except Exception as exc:
        raise HTTPException(status_code=503, detail="Coding model is unavailable. Check the configured model provider.") from exc
    if not result or not result.strip():
        raise HTTPException(status_code=503, detail="The coding model returned an empty response.")
    return {
        "ok": True,
        "mode": payload.mode,
        "language": payload.language,
        "result": result,
        "executed": False,
        "verification_note": "This response was generated by the configured model. Code execution and test results are not verified by this endpoint.",
    }
